# This file contains values from Cookiecutter

default_context:
  project_name: "portsel"
  project_description: "Easy financial portfolio selection."
  organization: "Thomas Battenfeld"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "thomasbtf"
  email: "thomas.battenfeld@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
